---

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - config_vars.yml
  tasks:

    # Docker Driver
    - block:
        - name: Build an Ansible compatible Docker image
          docker_image:
            path: "."
            name: "{{ docker_image_name }}"
            dockerfile: "{{ docker_image_file[molecule_target_distro] }}"

        - name: Start Gerrit DB container
          docker_container:
            name: "{{ docker_container_name_mysql }}"
            image: "{{ docker_image_name_mysql }}"
            state: started
            recreate: yes
            env:
              MYSQL_ROOT_PASSWORD: 1qazxsw2
              MYSQL_USER: gerrit
              MYSQL_PASSWORD: gerrit
              MYSQL_DATABASE: gerrit

        - name: Create molecule Docker instance(s)
          docker_container:
            name: "{{ item.name }}"
            hostname: "{{ item.name }}"
            image: "{{ docker_image_name }}"
            privileged: yes
            command: "{{ docker_command[molecule_target_distro] }}"
            volumes:
              # Mount the cgroups fs to allow SystemD to run into the containers
              - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
            recreate: no
            state: started
            links:
              - "{{ docker_container_name_mysql }}:{{ docker_container_name_mysql }}"
          with_items: "{{ molecule_yml.platforms }}"
      when: molecule_driver_name == 'docker'
